# Generated by Django 5.2.7 on 2025-10-19 02:15

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre Empresa')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=19.0, max_digits=5)),
                ('currency', models.CharField(default='CLP', max_length=3)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'companies',
                'indexes': [models.Index(fields=['rut'], name='idx_comp_rut'), models.Index(fields=['is_active'], name='idx_comp_active')],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('has_credit', models.BooleanField(default=False)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('current_debt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('has_discount', models.BooleanField(default=False)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='api.company')),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='BarcodeReaderConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('port', models.CharField(max_length=50)),
                ('baud_rate', models.IntegerField(default=9600)),
                ('data_bits', models.IntegerField(default=8)),
                ('parity', models.CharField(default='None', max_length=10)),
                ('stop_bits', models.IntegerField(default=1)),
                ('flow_control', models.CharField(default='None', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcode_configs', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcode_configs', to='api.company')),
            ],
            options={
                'db_table': 'barcode_configurations',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.company'),
        ),
        migrations.CreateModel(
            name='Consignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consignment_number', models.CharField(blank=True, db_index=True, default='TEMP-00000', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('partially_settled', 'Liquidada Parcialmente'), ('settled', 'Liquidada'), ('cancelled', 'Cancelada')], db_index=True, default='active', max_length=30)),
                ('delivery_date', models.DateTimeField(auto_now_add=True)),
                ('expected_return_date', models.DateField()),
                ('settlement_date', models.DateTimeField(blank=True, null=True)),
                ('total_delivered_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_sold_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_returned_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('delivery_notes', models.TextField(blank=True, null=True)),
                ('settlement_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consignments', to='api.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consignments', to='api.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consignments_created', to=settings.AUTH_USER_MODEL)),
                ('settled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consignments_settled', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consignments',
                'ordering': ['-delivery_date'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='api.company')),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.company')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.department')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('route', models.CharField(max_length=200)),
                ('association', models.CharField(blank=True, max_length=100, null=True)),
                ('icon_association', models.CharField(blank=True, max_length=100, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('parent_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.page')),
            ],
            options={
                'db_table': 'pages',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('resource', models.CharField(max_length=50)),
                ('action', models.CharField(choices=[('view', 'Ver'), ('create', 'Crear'), ('edit', 'Editar'), ('delete', 'Eliminar'), ('export', 'Exportar'), ('import', 'Importar'), ('approve', 'Aprobar')], max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'permissions',
                'indexes': [models.Index(fields=['resource', 'action'], name='idx_perm_res_act')],
                'unique_together': {('resource', 'action')},
            },
        ),
        migrations.CreateModel(
            name='PrinterConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('printer_name', models.CharField(max_length=200)),
                ('font_family', models.CharField(default='Arial', max_length=100)),
                ('font_size', models.IntegerField(default=12)),
                ('columns', models.IntegerField(default=40)),
                ('use_bold', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printer_configs', to='api.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printer_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'printer_configurations',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('barcode', models.CharField(max_length=50, unique=True)),
                ('barcode_package', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('stock_units', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_package', models.BooleanField(default=False)),
                ('units_per_package', models.IntegerField(blank=True, null=True)),
                ('is_tray', models.BooleanField(default=False)),
                ('packages_per_tray', models.IntegerField(blank=True, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('package_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tray_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('has_returnable_container', models.BooleanField(default=False)),
                ('container_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_tax_exempt', models.BooleanField(default=False)),
                ('variable_tax_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.company')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='api.department')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='DefectiveProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('defective', 'Defectuoso'), ('replaced', 'Reemplazado'), ('removed', 'Eliminado')], default='defective', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_defectives', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_defectives', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defective_records', to='api.product')),
            ],
            options={
                'db_table': 'defective_products',
            },
        ),
        migrations.CreateModel(
            name='ConsignmentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delivered_quantity', models.DecimalField(decimal_places=3, help_text='Cantidad entregada al cliente', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('sold_quantity', models.DecimalField(decimal_places=3, default=0, help_text='Cantidad vendida por el cliente', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('returned_quantity', models.DecimalField(decimal_places=3, default=0, help_text='Cantidad devuelta por el cliente', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.consignment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consignment_items', to='api.product')),
            ],
            options={
                'db_table': 'consignment_items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('promotion_type', models.CharField(choices=[('quantity_discount', 'Descuento por Cantidad'), ('free_units', 'Unidades Gratis (2x1, 3x2, etc.)'), ('percentage', 'Porcentaje de Descuento'), ('fixed_price', 'Precio Fijo')], max_length=30)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('min_quantity', models.IntegerField(blank=True, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('buy_quantity', models.IntegerField(blank=True, null=True)),
                ('free_quantity', models.IntegerField(blank=True, null=True)),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='api.company')),
            ],
            options={
                'db_table': 'promotions',
            },
        ),
        migrations.CreateModel(
            name='PromotionProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='api.product')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.promotion')),
            ],
            options={
                'db_table': 'promotion_products',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'En Espera'), ('cancelled', 'Cancelada'), ('paid', 'Pagada'), ('partial', 'Pago Parcial')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='api.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'purchase_orders',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_code', models.CharField(blank=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=19.0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.department')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='api.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.purchaseorder')),
            ],
            options={
                'db_table': 'purchase_order_items',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('master_admin', 'Master Admin'), ('super_admin', 'Super Admin'), ('admin', 'Administrador'), ('cashier', 'Cajero'), ('employee', 'Empleado')], max_length=50)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('hierarchy_level', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='api.company')),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='api.role'),
        ),
        migrations.CreateModel(
            name='RolePageAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('can_access', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.page')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_accesses', to='api.role')),
            ],
            options={
                'db_table': 'role_page_access',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_granted', models.BooleanField(default=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='api.role')),
            ],
            options={
                'db_table': 'role_permissions',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sale_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('invoice_number', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('sale_type', models.CharField(choices=[('regular', 'Venta Regular'), ('credit', 'Venta a Crédito'), ('consignment', 'Consignación')], db_index=True, default='regular', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completada'), ('cancelled', 'Cancelada'), ('refunded', 'Reembolsada')], db_index=True, default='pending', max_length=20)),
                ('sale_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_cancelled', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='api.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='api.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('paid', 'Pagado'), ('overdue', 'Vencido')], default='active', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='api.client')),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to='api.sale')),
            ],
            options={
                'db_table': 'credits',
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='api.product')),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='api.promotion')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.sale')),
            ],
            options={
                'db_table': 'sale_items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('debit', 'Débito'), ('credit_card', 'Tarjeta de Crédito'), ('transfer', 'Transferencia'), ('check', 'Cheque'), ('credit', 'Crédito')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.sale')),
            ],
            options={
                'db_table': 'sale_payments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shift_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('closed', 'Cerrado')], db_index=True, default='open', max_length=20)),
                ('opening_cash', models.DecimalField(decimal_places=2, help_text='Efectivo inicial en caja', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('expected_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_card', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_transfer', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('closing_card', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('closing_transfer', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('closing_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cash_difference', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('card_difference', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transfer_difference', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_difference', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('opened_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('opening_notes', models.TextField(blank=True, null=True)),
                ('closing_notes', models.TextField(blank=True, null=True)),
                ('lunch_break_start', models.DateTimeField(blank=True, null=True)),
                ('lunch_break_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts_closed', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='api.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shifts',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='api.shift'),
        ),
        migrations.CreateModel(
            name='CreditPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('debit', 'Débito'), ('credit_card', 'Tarjeta de Crédito'), ('transfer', 'Transferencia')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.credit')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_payments', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_payments', to='api.shift')),
            ],
            options={
                'db_table': 'credit_payments',
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('income', 'Ingreso'), ('expense', 'Egreso'), ('withdrawal', 'Retiro'), ('deposit', 'Depósito')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reason', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements_created', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_movements', to='api.shift')),
            ],
            options={
                'db_table': 'cash_movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashCount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('count_20000', models.PositiveIntegerField(default=0, verbose_name='$20.000')),
                ('count_10000', models.PositiveIntegerField(default=0, verbose_name='$10.000')),
                ('count_5000', models.PositiveIntegerField(default=0, verbose_name='$5.000')),
                ('count_2000', models.PositiveIntegerField(default=0, verbose_name='$2.000')),
                ('count_1000', models.PositiveIntegerField(default=0, verbose_name='$1.000')),
                ('count_500', models.PositiveIntegerField(default=0, verbose_name='$500')),
                ('count_100', models.PositiveIntegerField(default=0, verbose_name='$100')),
                ('count_50', models.PositiveIntegerField(default=0, verbose_name='$50')),
                ('count_10', models.PositiveIntegerField(default=0, verbose_name='$10')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_counts', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_counts', to='api.shift')),
            ],
            options={
                'db_table': 'cash_counts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('reset', 'Reinicio de Stock'), ('adjustment', 'Ajuste Manual'), ('bulk_update', 'Actualización Masiva'), ('import', 'Importación')], db_index=True, max_length=30)),
                ('description', models.TextField()),
                ('affected_products_count', models.IntegerField(default=0)),
                ('before_data', models.JSONField(blank=True, help_text='Estado antes del cambio', null=True)),
                ('after_data', models.JSONField(blank=True, help_text='Estado después del cambio', null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('requires_approval', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_audits', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_audits', to='api.company')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stock_audits',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('representative', models.CharField(blank=True, max_length=200)),
                ('phone_1', models.CharField(blank=True, max_length=20)),
                ('phone_2', models.CharField(blank=True, max_length=20)),
                ('email_1', models.EmailField(blank=True, max_length=254)),
                ('email_2', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='api.company')),
            ],
            options={
                'db_table': 'suppliers',
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='api.supplier'),
        ),
        migrations.CreateModel(
            name='ProductSupplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supplier_product_code', models.CharField(blank=True, max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_relations', to='api.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_relations', to='api.supplier')),
            ],
            options={
                'db_table': 'product_suppliers',
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('check', 'Cheque'), ('card', 'Tarjeta'), ('transfer', 'Transferencia')], max_length=20)),
                ('payment_source', models.CharField(choices=[('cash_register', 'Caja'), ('external', 'Entrega Externa')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivered_payments', to=settings.AUTH_USER_MODEL)),
                ('delivery_registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_payments', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.purchaseorder')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments', to='api.shift')),
            ],
            options={
                'db_table': 'supplier_payments',
            },
        ),
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('low_stock', 'Stock Bajo'), ('supplier_payment', 'Pago a Proveedor'), ('overdue_credit', 'Crédito Vencido'), ('system', 'Sistema')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('unread', 'No Leída'), ('read', 'Leída'), ('dismissed', 'Descartada')], default='unread', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='api.company')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.product')),
                ('supplier_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.supplierpayment')),
            ],
            options={
                'db_table': 'system_alerts',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('printed', 'Impreso'), ('cancelled', 'Cancelado')], db_index=True, default='pending', max_length=20)),
                ('ticket_data', models.JSONField(help_text='Datos del ticket en formato JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='api.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tickets', to=settings.AUTH_USER_MODEL)),
                ('printed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='printed_tickets', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='api.sale')),
            ],
            options={
                'db_table': 'tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LastPrintedTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='last_printed_ticket', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_printed_by_users', to='api.ticket')),
            ],
            options={
                'db_table': 'last_printed_tickets',
            },
        ),
        migrations.CreateModel(
            name='UserAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_alerts', to='api.systemalert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_alerts',
            },
        ),
        migrations.CreateModel(
            name='UserPageAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('can_access', models.BooleanField(default=False)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.page')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_page_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_page_access',
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_granted', models.BooleanField(default=False)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_permissions',
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['company', 'rut'], name='idx_client_comp_rut'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['has_credit'], name='idx_client_credit'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['is_active'], name='idx_client_active'),
        ),
        migrations.AddIndex(
            model_name='barcodereaderconfiguration',
            index=models.Index(fields=['user', 'is_active'], name='idx_bc_usr_active'),
        ),
        migrations.AddIndex(
            model_name='consignment',
            index=models.Index(fields=['company', 'client'], name='idx_cons_comp_cus'),
        ),
        migrations.AddIndex(
            model_name='consignment',
            index=models.Index(fields=['status', 'delivery_date'], name='idx_cons_st_date'),
        ),
        migrations.AddIndex(
            model_name='consignment',
            index=models.Index(fields=['consignment_number'], name='idx_cons_number'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['company', 'name'], name='idx_dept_comp_name'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['slug'], name='idx_dept_slug'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('company', 'name'), ('company', 'slug')},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['company', 'department'], name='idx_cat_comp_dept'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='idx_cat_slug'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('company', 'department', 'name'), ('company', 'department', 'slug')},
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['name'], name='idx_page_name'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['route'], name='idx_page_route'),
        ),
        migrations.AddIndex(
            model_name='printerconfiguration',
            index=models.Index(fields=['user', 'is_active'], name='idx_pc_usr_active'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company', 'barcode'], name='idx_prod_comp_bar'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='idx_prod_name'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['department'], name='idx_prod_dept'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='idx_prod_active'),
        ),
        migrations.AddIndex(
            model_name='defectiveproduct',
            index=models.Index(fields=['product', 'status'], name='idx_def_prod_stat'),
        ),
        migrations.AddIndex(
            model_name='defectiveproduct',
            index=models.Index(fields=['registered_at'], name='idx_def_reg_at'),
        ),
        migrations.AddIndex(
            model_name='consignmentitem',
            index=models.Index(fields=['consignment', 'product'], name='idx_citem_con_pro'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['company', 'is_active'], name='idx_prom_comp_act'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['start_date', 'end_date'], name='idx_prom_dates'),
        ),
        migrations.AddIndex(
            model_name='promotionproduct',
            index=models.Index(fields=['promotion', 'product'], name='idx_pp_prom_prod'),
        ),
        migrations.AlterUniqueTogether(
            name='promotionproduct',
            unique_together={('promotion', 'product')},
        ),
        migrations.AddIndex(
            model_name='purchaseorderitem',
            index=models.Index(fields=['purchase_order'], name='idx_poi_po'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['company', 'name'], name='idx_role_comp_nm'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['hierarchy_level'], name='idx_role_hier'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('company', 'name')},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['company', 'email'], name='idx_usr_comp_email'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['rut'], name='idx_usr_rut'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='idx_usr_active'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='idx_usr_role'),
        ),
        migrations.AddIndex(
            model_name='rolepageaccess',
            index=models.Index(fields=['role', 'page'], name='idx_rpa_role_page'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepageaccess',
            unique_together={('role', 'page')},
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['role', 'permission'], name='idx_rp_role_perm'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AddIndex(
            model_name='credit',
            index=models.Index(fields=['client', 'status'], name='idx_cred_cli_stat'),
        ),
        migrations.AddIndex(
            model_name='credit',
            index=models.Index(fields=['status'], name='idx_cred_status'),
        ),
        migrations.AddIndex(
            model_name='credit',
            index=models.Index(fields=['due_date'], name='idx_cred_due'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['sale', 'product'], name='idx_sitem_sal_pro'),
        ),
        migrations.AddIndex(
            model_name='salepayment',
            index=models.Index(fields=['sale', 'payment_method'], name='idx_spay_sal_meth'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['company', 'user', 'status'], name='idx_shift_co_us_s'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['opened_at'], name='idx_shift_opened'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['company', 'sale_date'], name='idx_sale_co_date'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['status', 'sale_type'], name='idx_sale_st_type'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['client', 'sale_date'], name='idx_sale_cu_date'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['shift'], name='idx_sale_shift'),
        ),
        migrations.AddIndex(
            model_name='creditpayment',
            index=models.Index(fields=['credit'], name='idx_cp_credit'),
        ),
        migrations.AddIndex(
            model_name='creditpayment',
            index=models.Index(fields=['created_at'], name='idx_cp_created'),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['shift', 'movement_type'], name='idx_cmov_sh_type'),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['created_at'], name='idx_cmov_created'),
        ),
        migrations.AddIndex(
            model_name='stockaudit',
            index=models.Index(fields=['company', 'action_type'], name='idx_audit_comp_act'),
        ),
        migrations.AddIndex(
            model_name='stockaudit',
            index=models.Index(fields=['performed_at'], name='idx_audit_date'),
        ),
        migrations.AddIndex(
            model_name='stockaudit',
            index=models.Index(fields=['performed_by'], name='idx_audit_user'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['company', 'name'], name='idx_supp_comp_name'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['is_active'], name='idx_supp_active'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['company', 'status'], name='idx_po_comp_stat'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier'], name='idx_po_supplier'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['created_at'], name='idx_po_created'),
        ),
        migrations.AddIndex(
            model_name='productsupplier',
            index=models.Index(fields=['product', 'supplier'], name='idx_ps_prod_supp'),
        ),
        migrations.AlterUniqueTogether(
            name='productsupplier',
            unique_together={('product', 'supplier')},
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['purchase_order'], name='idx_sp_po'),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['payment_date'], name='idx_sp_date'),
        ),
        migrations.AddIndex(
            model_name='systemalert',
            index=models.Index(fields=['company', 'status'], name='idx_alert_comp_st'),
        ),
        migrations.AddIndex(
            model_name='systemalert',
            index=models.Index(fields=['alert_type'], name='idx_alert_type'),
        ),
        migrations.AddIndex(
            model_name='systemalert',
            index=models.Index(fields=['created_at'], name='idx_alert_created'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['company', 'status'], name='idx_ticket_comp_st'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['sale'], name='idx_ticket_sale'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_at'], name='idx_ticket_created'),
        ),
        migrations.AddIndex(
            model_name='useralert',
            index=models.Index(fields=['user', 'is_read'], name='idx_ua_usr_read'),
        ),
        migrations.AlterUniqueTogether(
            name='useralert',
            unique_together={('alert', 'user')},
        ),
        migrations.AddIndex(
            model_name='userpageaccess',
            index=models.Index(fields=['user', 'page'], name='idx_upa_usr_page'),
        ),
        migrations.AlterUniqueTogether(
            name='userpageaccess',
            unique_together={('user', 'page')},
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['user', 'permission'], name='idx_up_usr_perm'),
        ),
        migrations.AlterUniqueTogether(
            name='userpermission',
            unique_together={('user', 'permission')},
        ),
    ]
